name: comp2322-coursework
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - array
  - bytestring
  - text
  - mtl
  - rdf4h

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  exposed-modules:
    - AST
    - Lexer
    - Parser
    - Evaluator

executables:
  tsparq:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
    dependencies:
      - comp2322-coursework

tests:
  coursework-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - comp2322-coursework
      - hspec
